### ISSUE TITLE
Crashes Seconds after startup

### ISSUE THREAD

**Issue by DamageIncorporated** [markusfisch/BinaryEye#21]
I see the camera image for about 1-2 seconds, then the App quits silently to the launcher.

Device: Samsong Galaxy S5 SM G900F 
Android 9
LineageOS 16-microG (no Google Services) klte

I can provide additional information, but need instructions on how to do that ;)

**Comment by markusfisch** [comment]
Thanks for reporting! Hm, is it the latest beta version 1.4.3 or is it the release version 1.3.7 or 1.3.8 (if you got it from F-Droid)? You should see the version in Settings -> Apps -> Binary Eye.

**Comment by nonnymoose** [comment]
This happens to me also on stock Android 8.1 with version 1.4.3 from F-Droid.

**Comment by markusfisch** [comment]
Hm, that's bad. Sounds like a RenderScript exception but I don't know what's going wrong yet. Maybe it's something device specific 🤔

Investigating.

**Comment by nonnymoose** [comment]
I also noticed the issue in 1.4.1 and 1.4.2. I'll email you a bug report from my device.

**Comment by markusfisch** [comment]
That would be great!

**Comment by tobiasisenberg** [comment]
I can confirm the crash behavior for a Samsung Galaxy S5 with a pure Lineage OS 16.0, no GApps, for version 1.4.3 from F-Droid. The same app runs fine on a different Android Pie device (but with Google's apps).

**Comment by nonnymoose** [comment]
Plot twist: It happens in 1.3.5 (from github) also.

**Comment by adyeths** [comment]
I have this problem as well on my android 8.0 phone, but only when I have it installed on the sd card instead of my phone's internal shared storage. When I move the app to the internal shared storage the problem goes away.

**Comment by nonnymoose** [comment]
Good catch! This is the case for me as well. I do hope it gets fixed
though, because I have 128gb of external storage and only 16gb of internal
storage.

**Comment by markusfisch** [comment]
Good catch indeed! This is really strange! 🤔 

Honestly, I have no clue what's causing this because the app doesn't write anything to disk when you're opening the camera.

**Comment by DamageIncorporated** [comment]
Sorry for the late reply... Today binary eye from f-droid updated to version 1.5.0 and the problem persists :-/

Another strange phenomenon I've just noticed: 
When BE has dropped me to the launcher, Android shows the dialog "App has repeatedly quit" and I press the option "quit app".

Then I choose "recent apps" (system butto ) and BE seems to be still running. 
I can select it, I see the camera view, but after seconds it crashes again ...

**Comment by markusfisch** [comment]
Hm, unfortunately, that was to be expected. Version 1.5.0 (or 1.5.1 now) doesn't change anything RenderScript related. And I know it's something about RenderScript because I can see a couple of 
`android.support.v8.renderscript.RSRuntimeException`s followed by some native `SIGSEV`s in Google's error tracking:
```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
android::renderscript::ObjectBase::decUserRef() const
```

But since I still can't reproduce the problem, I'm pretty much in the dark. Especially because moving the app from external to internal storage shouldn't make any difference for RenderScript at all. So I really need to find a device where that happens to make sense of this.

**Comment by markusfisch** [comment]
I think I found something: The RenderScript shared objects for arm64_v8a and x86_64 architectures were not created. After updating to RenderScript API 24 (Google recommends setting this value to the lowest API level able to provide all the functionality), the shared objects are generated again!

This was quite hard to spot because those libraries are only used on platforms where RenderScript isn't using the GPU but the CPU instead. Most x64 devices have GPU's that are good enough.

So Version 1.7.1, currently in beta, should fix this:
https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

The apk is here:
https://github.com/markusfisch/BinaryEye/releases

**Comment by markusfisch** [comment]
Hm, too bad, I really thought that would fix it.

Today, I've found someone with a Samsung Galaxy S5 with Lineage OS 16.0 and was able to witness the crash. The next thing I did was installing Google's RenderScript [sample app](https://github.com/googlesamples/android-BasicRenderScript) on that device and it crashed too, unfortunately.

So I'm still investigating the issue but it certainly looks like a system bug 😬

**Comment by markusfisch** [comment]
Too bad, I thought that was it. Hm.Am 08.05.2019 15:25 schrieb tobiasisenberg <notifications@github.com>:Same here, the beta still crashes on my Samsung Galaxy S5 with pure Lineage OS 16.0.

**Comment by markusfisch** [comment]
So, I've added a fallback if RenderScript fails: https://github.com/markusfisch/BinaryEye/commit/6b8dd8e86440165fe7e845d3c58aa1129cd818c1

It's in 1.7.2 now:
https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

APK:
https://github.com/markusfisch/BinaryEye/releases

**Comment by nonnymoose** [comment]
Unfortunately this is still crashing for me. I've got more time on my hands than I have in months later this week so I think I'll break out the debugger and try to find some more info for you.

**Comment by markusfisch** [comment]
That would be great! 👍 

Today I found out that RenderScript is crashing even earlier than I thought in 1.7.2 so there will be a 1.7.3 soon. Unfortunately, even catching the `RSRuntimeException` earlier this doesn't fix it completely. At least not for the Samsung Galaxy S5 with Lineage 16.0 I have access to 😞 

The problem - at least on this device - seems to be that `/system/bin/bcc` fails to compile the [rotator](https://github.com/markusfisch/BinaryEye/blob/master/app/src/main/rs/rotator.rs) script. Why? I have no idea yet.

Also, there's a log message saying `librs.rotator.so` could not be loaded but I can't see why. I found the file on the device exactly where it should be.

Now, if I catch the `RSRuntimeException` and continue without RenderScript, the app will crash with a SIGSEV in some RenderScript library (forgot which one) I am no longer using 🙈

**Comment by avoidr** [comment]
Hello, I have the very same problem and I am glad that you're working on this!

My device is also SM-G900F, LOS 16, no Google.
My binary eye version is 1.7.2.

Before I flashed LOS, I tried the app in OEM ROM and it worked there.

Thank you for your effort!

**Comment by nonnymoose** [comment]
So, here's what I found debugging:

- ~~Android _really_ hates debugging apps stored on external storage. `pm` would even move it into internal storage if used to install.~~
- I can confirm that RenderScript causes SIGSEGV if it fails to load your RenderScript kernels. Furthermore, I can confirm that the app does _not_ crash if it does not attempt to load RenderScript, i.e. everything else is the same.
- The reason that it can't load the RenderScript kernel from external storage but it can from internal is not due to `bcc` failing to compile the rotator script, but because the "rs" namespace (I don't know what kind of namespace this is) does not allow loading shared libraries from `/mnt/external/`, but it _does_ from `/data/`. Since it's working on a lot of other devices, I have to assume that this is a device specific bug. Here is the relevant error:  
`E/linker: library "/mnt/expand/fc0e42a4-30b8-49b3-86da-2727d2905b0f/user/0/de.markusfisch.android.binaryeye.debug/cache/librs.rotator.so" ("/mnt/expand/fc0e42a4-30b8-49b3-86da-2727d2905b0f/user/0/de.markusfisch.android.binaryeye.debug/cache/librs.rotator.so") needed or dlopened by "/system/lib64/vndk-sp/libRSCpuRef.so" is not accessible for the namespace: [name="rs", ld_library_paths="", default_library_paths="/system/lib64/vndk-sp:/vendor/lib64", permitted_paths="/vendor/lib64:/data"]`

I did find a solution, and I really hate saying it because I have _no idea_ why it works, but here it goes:

Forcing RenderScript to use the compatibility library instead of native using RenderScript.forceCompat() results in the script running successfully. I wish I knew what that did differently, because that would provide some insight into the device bugs causing this (and possibly the segfault too?).

Anyway, here's a diff:
```diff
diff --git a/app/src/main/kotlin/de/markusfisch/android/binaryeye/activity/CameraActivity.kt b/app/src/main/kotlin/de/markusfisch/android/binaryeye/activity/CameraActivity.kt
index c94d205..d2a2dfb 100644
--- a/app/src/main/kotlin/de/markusfisch/android/binaryeye/activity/CameraActivity.kt
+++ b/app/src/main/kotlin/de/markusfisch/android/binaryeye/activity/CameraActivity.kt
@@ -29,6 +29,7 @@ import android.support.v4.content.ContextCompat
 import android.support.v7.app.AppCompatActivity
 import android.support.v7.widget.Toolbar
 import android.support.v8.renderscript.RSRuntimeException
+import android.support.v8.renderscript.RenderScript
 import android.view.Menu
 import android.view.MenuItem
 import android.view.View
@@ -89,6 +90,9 @@ class CameraActivity : AppCompatActivity() {
 		flashFab = findViewById(R.id.flash)
 		flashFab.setOnClickListener { _ -> toggleTorchMode() }
 
+		if (useRenderScript) {
+			RenderScript.forceCompat()
+		}
 		initCameraView()
 		initZoomBar()
 		restoreZoom()
```

I've also attached an [apk](https://github.com/markusfisch/BinaryEye/files/3195897/app-release.apk.zip) (sorry about the zip; GitHub doesn't support apks in issues) for anyone who's affected who wants to try out this patch. Please note that it's signed with my key, not markusfisch's, so you will a) need to trust me :) and b) not be able to update the official app.

P.S. The people with LineageOS should consider reporting this issue if it doesn't occur on the stock ROM. I _am_ using stock, so I'm kind of stuck.

**Comment by markusfisch** [comment]
That's great! 👍Thanks a lot!!

I've just tried it on a range of devices just to check that `RenderScript.forceCompat()` doesn't have any negative impact on other devices and it works great everywhere! 😃 

Also, the solution works perfectly well for the S5 with Lineage 16.0 I have access to. So here's the commit https://github.com/markusfisch/BinaryEye/commit/b9e8f4cfcaca807307f68c25e584c5c13485a104 and there will be a new version by the end of the day.

Well done!
