### ISSUE TITLE
monochrome icon show error

### ISSUE THREAD

**Issue by Mystery00** [markusfisch/BinaryEye#339]
![image](https://user-images.githubusercontent.com/19162205/209920750-c1a503ce-7905-4e5e-a651-fe0db3b084f5.png)

**Comment by Mystery00** [comment]
The monochrome icon needs to use android:fillAlpha to represent the difference in color

**Comment by markusfisch** [comment]
Thanks for fixing this right away 👍

**Comment by tsiflimagas** [comment]
Was this fixed for you? It's still showing like that for me.

**Comment by Mystery00** [comment]
> Was this fixed for you? It's still showing like that for me. 

Maybe the latest version of Google play doesn't include this commit

**Comment by Mystery00** [comment]
> Was this fixed for you? It's still showing like that for me. 

Maybe the latest version of Google play doesn't include this commit

**Comment by tsiflimagas** [comment]
I'm on 1.58.0 which should include this commit.

**Comment by markusfisch** [comment]
Sorry, this isn't easy to test, unfortunately. Somehow I can't enable themed icons on my Pixel 7 🤔 

What devices are you on?

**Comment by Mystery00** [comment]
> Sorry, this isn't easy to test, unfortunately. Somehow I can't enable themed icons on my Pixel 7 🤔 
> 
> What devices are you on?

https://www.androidpolice.com/android-13-themed-icons-how-to-activate/ 

You can check out this tutorial to enable themed icons on Pixel 7, my device is Pixel 6 pro running Android 13

**Comment by markusfisch** [comment]
Well, I didn't have the "Themed icons" switch on my Pixel 7 Pro 🙈  But I found out it's because I don't use the Pixel launcher (I use my [own](https://github.com/markusfisch/PieLauncher) on all of my devices). Curiously, setting the Pixel launcher as the default launcher, doesn't immediately show the option too 🤷‍♂️ 

Anyway, I just used the emulator to enable themed icons and was able to debug the issue. I misunderstood how monochrome icons should be designed. This is now fixed in https://github.com/markusfisch/BinaryEye/commit/dfd64405da28d597d9cf02f5f6a4ceaf1cc50180

I will publish a new version soon. Thanks a lot for reporting! 👍

**Comment by tsiflimagas** [comment]
I made a debug build and I confirm the monochrome icon now looks good.
![Screenshot_20230130-230956_Arrow Launcher_1.png](https://user-images.githubusercontent.com/45879751/215596111-8b8428c9-46b4-4b17-ab18-b8c9a428a724.png)

**Comment by Mystery00** [comment]
> I made a debug build and I confirm the monochrome icon now looks good.
> ![Screenshot_20230130-230956_Arrow Launcher_1.png](https://user-images.githubusercontent.com/45879751/215596111-8b8428c9-46b4-4b17-ab18-b8c9a428a724.png)
> 
> 

Yep, that's weird why the version distributed by Google play shows the wrong monochrome icon

**Comment by tsiflimagas** [comment]
Because a866a2e didn't fix it, dfd6440 did, which is not in a release yet.

**Comment by tsiflimagas** [comment]
I think this can be closed now.
